### ISSUE TITLE
Error after update to v1.0.10

### ISSUE THREAD

**Issue by abdonrd** [0no-co/graphql.web#42]
### Describe the bug

In a Next.js v15 project, we are using `gql.tada`.
Currently the project is using the version `1.0.9` of `@0no-co/graphql.web`, and it's working fine!
But when we try to update to `1.0.10` (or `1.0.11`), we get this error:

```
 ⨯ ReferenceError: e is not defined
    at Module.Kind (/Users/abdonrd/project-name/.next/server/chunks/ssr/node_modules_cb980b._.js:8254:18)
    at Kind (node_modules/gql.tada/src/api.ts:334:44)
    at [project]/src/components/CompetitionLogo.tsx [app-rsc] (ecmascript) (src/components/CompetitionLogo.tsx:7:47)
    at instantiateModule (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/src/app/(home)/data.ts [app-rsc] (ecmascript) (src/app/(home)/data.ts:3:0)
    at instantiateModule (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/.next-internal/server/app/(home)/page/actions.js { ACTIONS_MODULE0 => "[project]/src/app/(home)/data.ts [app-rsc] (ecmascript)" } [app-rsc] (ecmascript) <module evaluation> (/Users/abdonrd/project-name/.next/server/chunks/ssr/_89b741._.js:820:134)
    at instantiateModule (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/.next-internal/server/app/(home)/page/actions.js { ACTIONS_MODULE0 => "[project]/src/app/(home)/data.ts [app-rsc] (ecmascript)" } [app-rsc] (ecmascript) (/Users/abdonrd/project-name/.next/server/chunks/ssr/_89b741._.js:842:334)
    at instantiateModule (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at instantiateRuntimeModule (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:652:12)
    at Object.getOrInstantiateRuntimeModule (/Users/abdonrd/project-name/.next/server/chunks/ssr/[turbopack]_runtime.js:668:12)
    at Object.<anonymous> (/Users/abdonrd/project-name/.next/server/app/(home)/page.js:16:9)
    at call (node_modules/next/src/server/require-hook.ts:70:25)
    at require (node_modules/next/src/server/require.ts:121:8)
    at page (node_modules/next/src/server/load-components.ts:189:41)
    at async DevServer.findPageComponentsImpl (node_modules/next/src/server/next-server.ts:779:27)
    at async DevServer.findPageComponents (node_modules/next/src/server/dev/next-dev-server.ts:881:13)
    at async DevServer.renderPageComponent (node_modules/next/src/server/base-server.ts:3584:19)
    at async DevServer.renderToResponseImpl (node_modules/next/src/server/base-server.ts:3659:23)
    at async DevServer.pipeImpl (node_modules/next/src/server/base-server.ts:1698:20)
    at async NextNodeServer.handleCatchallRenderRequest (node_modules/next/src/server/next-server.ts:1034:6)
    at async DevServer.handleRequestImpl (node_modules/next/src/server/base-server.ts:1462:8)
    at async (node_modules/next/src/server/dev/next-dev-server.ts:514:13)
    at async Span.traceAsyncFn (node_modules/next/src/trace/trace.ts:143:13)
    at async DevServer.handleRequest (node_modules/next/src/server/dev/next-dev-server.ts:512:19)
    at async invokeRender (node_modules/next/src/server/lib/router-server.ts:284:10)
    at async handleRequest (node_modules/next/src/server/lib/router-server.ts:530:15)
    at async requestHandlerImpl (node_modules/next/src/server/lib/router-server.ts:576:6)
    at async Server.requestListener (node_modules/next/src/server/lib/start-server.ts:146:6)
  332 |     let isFragment: boolean;
  333 |     if (
> 334 |       (isFragment = definitions[0].kind === Kind.FRAGMENT_DEFINITION) &&
      |                                            ^
  335 |       definitions[0].directives
  336 |     ) {
  337 |       definitions[0].directives = definitions[0].directives.filter( {
  page: '/'
}
 GET / 500 in 105ms
```

### Reproduction

TODO

### Package version

@0no-co/graphql.web@1.0.10

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which GitHub Discussions should be used
- [X] Follow our [Code of Conduct](https://github.com/0no-co/graphql.web/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
See: https://github.com/urql-graphql/urql/issues/3704#issuecomment-2452791524
It's not an issue on our end and nothing we can do about it. You can examine the bundle, which should make it pretty clear that the bundle itself for `graphql.web` is fine.

**Comment by apostolos** [comment]
@kitten Please read this comment https://github.com/vercel/next.js/issues/72232#issuecomment-2466189331

I think the bundler's behavior is correct (in assuming readonly properties shouldn't have setters). Please consider an alternative on your end.

**Comment by apostolos** [comment]
Thanks for the explanation @kitten. Do you mind if I share your response in the original Next.js thread, so the Turbopack people are more likely to read it?

**Comment by kitten** [comment]
I'm not sure it's relevant yet for the Next repo or Turbopack team per se. I assume, if this transformation is happening, it'd still be important for us to see what that transformation is
(as in, a desymbolicated stack trace or output code is still useful here). Because that allows us to see if or what's wrong and look at possible workarounds that still work for `graphql-tag`.

Other than that, the problem here is that we're now potentially working within the constraints of `graphql-tag` _and_ Turbopack, if we can confirm what's wrong. It'd hence be useful to boil this down into a smaller piece of feedback (or an issue report) for the Turbopack team

**Comment by abdonrd** [comment]
Seems like they are working on a fix here:
- https://github.com/vercel/next.js/pull/73544

**Comment by abdonrd** [comment]
Fixed on **Next.js v15.2.2**:
https://github.com/vercel/next.js/releases/tag/v15.2.2
